add rails project.
planningdev/pnd_server_calendar pull request #2
Opened 2018-11-13 08:13 UTC by naoto67

railsアプリを追加しました。

2018-11-13 08:20 UTC, Ko1103 requested changes
READMEに
```
🈲bundle update
```
と明記してくれ

2018-11-13 08:20 UTC, Ko1103 commented on .gitignore
> +/config/master.key
これを追加して欲しい
```
# Ignore uploaded files in development
/storage/*
!/storage/.keep
```

2018-11-13 08:28 UTC, Ko1103 commented
#環境
- ruby 2..5.3
- rails 5.2.1 ~

❌ bundle update は絶対にしないで

2018-11-13 08:32 UTC, merged

2018-11-13 08:33 UTC, Ko1103 commented
LGTM

2018-11-17 03:53 UTC, 1060ki reviewed
Mergedだけど一応コメントした

2018-11-17 03:53 UTC, 1060ki commented on README.md
> + bundle update は絶対にしないで
bundle updateしないということはGemの脆弱性やバグそのままにすること。
bundle updateしてもいいようにテストを書くとか、更新されたくないGemにはバージョン指定をするべき。

2018-11-17 03:53 UTC, 1060ki commented on README.md
> + bundle update は絶対にしないで
@Ko1103 の意図はわからんけど。